[package]
name = "spawn"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
arboard = "3.6.1"
clap ={ version = "4.5.48", features = ["derive"] }
uuid = { version = "1.18.1", features = ["v4"] }
